### PR TITLE
Fix SSL test issue

### LINKED ISSUE #932: OpenSSL issues in Fedora
When I run the test suite in Fedora, I get:

```
  1) Error:
SslTest#test_verified_ssl_connection:
OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/connection/ruby.rb:255:in `connect_nonblock'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/connection/ruby.rb:255:in `connect'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/connection/ruby.rb:297:in `connect'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:349:in `establish_connection'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:381:in `ensure_connected'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:233:in `block in process'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:320:in `logging'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:232:in `process'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:126:in `call'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis.rb:172:in `block in ping'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
    /usr/share/ruby/monitor.rb:202:in `synchronize'
    /usr/share/ruby/monitor.rb:202:in `mon_synchronize'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis.rb:171:in `ping'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/test/ssl_test.rb:19:in `block in test_verified_ssl_connection'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/test/support/redis_mock.rb:70:in `start_with_handler'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/test/support/redis_mock.rb:128:in `start'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/test/ssl_test.rb:17:in `test_verified_ssl_connection'

  2) Error:
SslTest#test_ssl_blocking:
OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/connection/ruby.rb:255:in `connect_nonblock'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/connection/ruby.rb:255:in `connect'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/connection/ruby.rb:297:in `connect'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:349:in `establish_connection'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:381:in `ensure_connected'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:233:in `block in process'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:320:in `logging'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:232:in `process'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:126:in `call'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis.rb:848:in `block in set'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
    /usr/share/ruby/monitor.rb:202:in `synchronize'
    /usr/share/ruby/monitor.rb:202:in `mon_synchronize'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis.rb:844:in `set'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/test/ssl_test.rb:44:in `block in test_ssl_blocking'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/test/support/redis_mock.rb:70:in `start_with_handler'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/test/support/redis_mock.rb:128:in `start'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/test/ssl_test.rb:42:in `test_ssl_blocking'

```

Test suite is executed during build like so:
```
$ export DRIVER=ruby
$ make TIMEOUT=15 BINARY=/usr/bin/redis-server REDIS_CLIENT=/usr/bin/redis-cli 'BUILD_DIR=${TMP}'
```

This was previously fine, the OpenSSL, but ciphers are probably stricter now.

### PR DESCRIPTION
**Pull request by supercaracal**
This PR will resolve #932.

I also experienced the issue on my Ubuntu, so I executed the following commands, then the test cases was succeeded.

```
$ pwd
/path/to/redis-rb/test/support/ssl
$ bash gen_certs.sh
```

Here my environment information is.

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

```
$ openssl version
OpenSSL 1.1.1f  31 Mar 2020
```

```
$ ruby --version
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]
```

https://github.com/redis/redis/blob/64c360c5156ca6ee6d1eb52bfeb3fa48f3b25da5/src/tls.c#L177-L178
https://github.com/redis/redis-rb#ssltls-support

### CODE REVIEW

**Comment by supercaracal** [comment]
Also, I would hope that #930 is merged if it is legit.

File: test/support/ssl/gen_certs.sh [hunk 1]
```diff
@@ -19,8 +19,8 @@ for type in trusted untrusted; do
   mkdir -p ./demoCA/private
   touch ./demoCA/index.txt
 
-  openssl genrsa -out ${type}-ca.key 2048
-  openssl req -new -x509 -days 12500 -key ${type}-ca.key -out ${type}-ca.crt -subj "$(get_subject $type)"
+  openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out ${type}-ca.key
+  openssl req -new -x509 -days 12500 -key ${type}-ca.key -sha256 -out ${type}-ca.crt -subj "$(get_subject $type)"
```
Comment (supercaracal) [inline test/support/ssl/gen_certs.sh:23]: > SSL_CTX_use_certificate: ca md too weak
